const fs = require('fs')
const t = fs.readFileSync('scripts/harness/evidence.ts', 'utf8')
const i = t.indexOf('export type EvidenceInput')
console.log(t.slice(i, i + 900))
const a = fs.readFileSync('scripts/harness/adapters.ts', 'utf8')
const j = a.indexOf('phase3.sec32_controlled_shock')
console.log('--- adapter block ---')
console.log(a.slice(j - 150, j + 750))
const k = a.indexOf("test: 'wp11")
console.log('--- sample mech ---')
const m = a.indexOf("channel: 'MECHANISM'")
console.log(a.slice(m - 80, m + 450))