const fs = require('fs')
const t = fs.readFileSync('src/lib/sim/behaviors.ts', 'utf8')
const i = t.indexOf("noteChosenAction(v, 'takeFromChest', 'survie")
console.log('try', JSON.stringify(t.slice(i - 320, i + 40)))
const j = t.indexOf("noteChosenAction(v, 'takeFromChest', 'faim")
console.log('int', JSON.stringify(t.slice(j - 360, j + 40)))
