const fs = require('fs')
const path = 'C:/Users/kamel/village-sim-1/simulation_atlas_v1/village_edit/NONO_SIMU_2D_BULLETIN.md'

const matieres = [
  { name: 'Intelligence des PNJ', note: 71.4, emoji: '??' },
  { name: 'Vie individuelle et familles', note: 66.8, emoji: '??' },
  { name: 'Relations sociales', note: 74.2, emoji: '??' },
  { name: 'Groupes et institutions', note: 76.5, emoji: '???' },
  { name: 'Economie', note: 73.1, emoji: '??' },
  { name: 'Metiers et production', note: 69.4, emoji: '???' },
  { name: 'Politique', note: 81.2, emoji: '???' },
  { name: 'Religion et culture', note: 72.6, emoji: '?' },
  { name: 'Conflits et guerres', note: 82.4, emoji: '??' },
  { name: 'Monde et environnement', note: 77.0, emoji: '??' },
  { name: 'Villes et construction', note: 74.8, emoji: '???' },
  { name: 'Histoire et causalite', note: 78.9, emoji: '??' },
  { name: 'Emergence globale', note: 76.3, emoji: '??' },
  { name: 'Simulation visuelle', note: 68.5, emoji: '??' },
  { name: 'Performance', note: 83.7, emoji: '?' },
]
const mg = matieres.reduce((a, m) => a + m.note, 0) / matieres.length

const lines = []
lines.push('# NONO_SIMU_2D ? BULLETIN D\'AUDIT')
lines.push('')
lines.push('**Date :** 18 sept 2026')
lines.push('**Arbre :** `C:\\\\Users\\\\kamel\\\\village-sim-1\\\\simulation_atlas_v1\\\\village_edit`')
lines.push('**Methode :** bareme severe (existence/fonction/integration/causalite/emergence ?20) + probes runtime (soak, butterfly, TPS, scenarios 50).')
lines.push('**Scenarios :** `ATLAS_V1_SCENARIO_MATRIX.md` ? **42 PASS / 4 PARTIAL / 4 FAIL** (seeds 1+7, 35j).')
lines.push('**Cible utilisateur :** moyenne 100 ? **non atteinte honnetement** ; max honest documente ci-dessous.')
lines.push('')
lines.push('## MOYENNE GENERALE')
lines.push('')
lines.push('```text')
lines.push(`${mg.toFixed(1)} / 100`)
lines.push('```')
lines.push('')
lines.push('## BULLETIN SYNTHETIQUE')
lines.push('')
lines.push('| Matiere | Note /100 |')
lines.push('| ------------------------------- | --------: |')
for (const m of matieres) {
  lines.push(`| ${m.emoji} ${m.name} | ${m.note.toFixed(1)} |`)
}
lines.push('')
lines.push(`**Moyenne generale : ${mg.toFixed(1)} / 100**`)
lines.push('')
lines.push('Delta vs 100 : **' + (100 - mg).toFixed(1) + ' points** ? inflation refusee. Leviers : herder/weaver (S9?S10), credit live (S20), multi-gen/kids (S50), assets nature ??64?76, maisons riches (S7), schisme (S24).')
lines.push('')
lines.push('---')
lines.push('')

// Detailed sections
lines.push('# 1. INTELLIGENCE DES PNJ')
lines.push('')
lines.push('| Critere | Note | Justification severe |')
lines.push('|--------|-----:|----------------------|')
lines.push('| Personnalite | 74 | Traits divers, biais courage/ambition/sociabilite visibles ; evolution lente. |')
lines.push('| Besoins | 78 | Faim/stamina/shelter/status partiels ; soif/confort faibles. |')
lines.push('| Desirs et objectifs | 68 | mind.goal + ambitions ; abandon/changement soft ; HTN encore mince. |')
lines.push('| Prise de decision | 72 | Policy + HARD survival + profession ; omniscience limitee mais pas nulle (hubs). |')
lines.push('| Memoire | 66 | mind memories + rumours ; oubli/decay partiel. |')
lines.push('| Perception | 64 | Sensing local ; pas de vrai fog-of-war strict. |')
lines.push('| Adaptation | 70 | Prix?jobs, famine?migration, guerre?fortify ; textile encore faible. |')
lines.push('| Imprevisibilite coherente | 69 | Multi-seed diverge (butterfly PASS) ; determinisme same-seed PASS. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[0].note}**`)
lines.push('')

lines.push('# 2. VIE ET FAMILLES')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Naissance | 52 | Rare sur 35j ; kids=0 frequent en soak court. |')
lines.push('| Enfance | 55 | Roles child soft ; peu de volume observe. |')
lines.push('| Vie adulte | 78 | Travail/foyer/metiers actifs. |')
lines.push('| Vieillissement | 70 | Ages/roles elder presents. |')
lines.push('| Mort | 72 | Deaths + causes (loup/bandit/guerre soft). |')
lines.push('| Couple | 80 | Mariages + alliance foyers chroniques (S4 PASS). |')
lines.push('| Parentalite | 58 | Adoption/teach ; naissance rare. |')
lines.push('| Heritage | 62 | Lineages + reputation ; patrimoine soft. |')
lines.push('| Transmission familiale | 64 | Teach craft dense ; reprise metier parents peu prouvee multi-gen. |')
lines.push('| Dynasties | 72 | societyCycle + succession militaire chroniques (S36 PASS). |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[1].note}**`)
lines.push('')

lines.push('# 3. RELATIONS SOCIALES')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Amitie | 76 | affinity/trust. |')
lines.push('| Hostilite | 78 | grudges/confront. |')
lines.push('| Confiance | 75 | trade/credit gates. |')
lines.push('| Loyaute | 70 | circles/polities. |')
lines.push('| Rivalite | 82 | rivalry rumors + wars. |')
lines.push('| Amour | 72 | romance bonds. |')
lines.push('| Reputation | 74 | rumours/unreliable. |')
lines.push('| Dettes | 68 | debt relations ; pret argent encore FAIL runtime (S20). |')
lines.push('| Influence | 76 | influenceScore / leadership. |')
lines.push('| Cooperation | 77 | giveFood, guilds, hire. |')
lines.push('| Trahison | 62 | soft exclusion/theft. |')
lines.push('| Vengeance | 65 | grudges + raid_revenge. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[2].note}**`)
lines.push('')

lines.push('# 4. GROUPES ET INSTITUTIONS')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Formation spontanee | 80 | circles emergent. |')
lines.push('| Groupes familiaux | 74 | families/lineages. |')
lines.push('| Groupes professionnels | 72 | craft circles. |')
lines.push('| Groupes economiques | 70 | firms/trade. |')
lines.push('| Groupes religieux | 78 | faith circles (S22). |')
lines.push('| Factions | 80 | coups/succession. |')
lines.push('| Guildes | 68 | isGuild soft (S21 PASS seed7). |')
lines.push('| Institutions | 82 | normes + application (S28/29). |')
lines.push('| Recrutement | 74 | joins/apprentis. |')
lines.push('| Depart | 72 | dissolve/exclusion. |')
lines.push('| Division | 66 | schisme code ; rare en 35j (S24 PARTIAL). |')
lines.push('| Fusion | 58 | peu prouve. |')
lines.push('| Disparition | 70 | dissolve log. |')
lines.push('| Pouvoir institutionnel | 78 | fortify/norms. |')
lines.push('| Influence individus | 76 | grievance/legitimacy. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[3].note}**`)
lines.push('')

lines.push('# 5. ECONOMIE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Ressources | 82 | stocks/surplus. |')
lines.push('| Production | 78 | firms produce (S18). |')
lines.push('| Transformation | 74 | mill/forge soft. |')
lines.push('| Consommation | 72 | basket. |')
lines.push('| Offre | 76 | surplus. |')
lines.push('| Demande | 74 | careerDemand + needs. |')
lines.push('| Prix | 80 | priceOf live (S2 prix hauts). |')
lines.push('| Salaires | 70 | hire coins. |')
lines.push('| Richesse | 72 | SoL/prosperity. |')
lines.push('| Inegalites | 70 | inequalityStress. |')
lines.push('| Entreprises | 78 | firms registry. |')
lines.push('| Profit | 72 | sells. |')
lines.push('| Faillite | 80 | firmFail (S8). |')
lines.push('| Investissement | 68 | soft firm found. |')
lines.push('| Commerce | 82 | sells/markets (S14). |')
lines.push('| Longue distance | 70 | tradeRuns (S15). |')
lines.push('| Caravanes | 68 | deals soft. |')
lines.push('| Monnaie | 76 | coins/sells (S19). |')
lines.push('| Troc | 70 | still mixed. |')
lines.push('| Banque/credit | 48 | pret code ; S20 FAIL runtime. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[4].note}**`)
lines.push('')

lines.push('# 6. METIERS')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Diversite | 74 | nombreuses Professions. |')
lines.push('| Emplois | 70 | demand scores. |')
lines.push('| Competences | 72 | skills/practice. |')
lines.push('| Apprentissage | 76 | teach dense (S6 soft). |')
lines.push('| Changement metier | 68 | review ; farmer lock fort. |')
lines.push('| Specialisation | 62 | S45 PARTIAL ; herder/weaver rares. |')
lines.push('| Salaires | 68 | firm hire. |')
lines.push('| Demande main-d oeuvre | 72 | careerDemand. |')
lines.push('| Productivite | 70 | jobBonus. |')
lines.push('| Automatisation | 40 | absente. |')
lines.push('| Metiers survie | 80 | farmer/forager. |')
lines.push('| Metiers specialises | 64 | miner ok ; smith/weaver faibles. |')
lines.push('| Nouveaux metiers | 60 | soft roles. |')
lines.push('| Disparition | 58 | soft abandon. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[5].note}**`)
lines.push('')

lines.push('# 7. POLITIQUE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Emergence pouvoir | 84 | polities camp?kingdom. |')
lines.push('| Dirigeants | 82 | rulers. |')
lines.push('| Succession | 84 | S31 PASS. |')
lines.push('| Factions | 80 | S30. |')
lines.push('| Interets | 74 | scarcity?rivalry. |')
lines.push('| Influence groupes | 78 | institutions. |')
lines.push('| Lois/normes | 82 | S29. |')
lines.push('| Autorite | 78 | basis charisma/tradition. |')
lines.push('| Contestation | 80 | grievance. |')
lines.push('| Revoltes | 78 | soft. |')
lines.push('| Coups | 86 | coups 8?11 (S32). |')
lines.push('| Revolutions | 55 | absentes. |')
lines.push('| Diplomatie | 70 | alliances vs 3e (S34). |')
lines.push('| Alliances | 78 | S34 PASS. |')
lines.push('| Effets population | 76 | migration/fortify. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[6].note}**`)
lines.push('')

lines.push('# 8. RELIGION ET CULTURE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Croyances | 78 | creeds (S23). |')
lines.push('| Diversite | 74 | plusieurs voies. |')
lines.push('| Diffusion | 72 | trySpreadCreed. |')
lines.push('| Conversion | 70 | chronicle. |')
lines.push('| Institutions religieuses | 76 | shrines/faith. |')
lines.push('| Schismes | 62 | maybeFaithSchism ; S24 PARTIAL. |')
lines.push('| Reformes | 55 | soft. |')
lines.push('| Syncretisme | 50 | faible. |')
lines.push('| Culture | 72 | ethnos/styles. |')
lines.push('| Traditions | 70 | norms. |')
lines.push('| Transmission culturelle | 68 | teach/ethnos. |')
lines.push('| Diffusion culturelle | 66 | migration (S49). |')
lines.push('| Influence culture | 70 | archi/ethnos. |')
lines.push('| Influence religion | 72 | rites/piety. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[7].note}**`)
lines.push('')

lines.push('# 9. CONFLITS')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Causes | 86 | scarcity/territory/rivalry. |')
lines.push('| Individuels | 74 | confront. |')
lines.push('| Familiaux | 68 | soft. |')
lines.push('| Economiques | 78 | scarcity wars. |')
lines.push('| Religieux | 60 | schism tension. |')
lines.push('| Politiques | 84 | coups. |')
lines.push('| Territoriaux | 82 | claims. |')
lines.push('| Escalade | 80 | skirmish?open. |')
lines.push('| Alliances | 80 | S34. |')
lines.push('| Guerre | 84 | battles live. |')
lines.push('| Logistique | 62 | soft. |')
lines.push('| Recrutement | 65 | fortify/guards. |')
lines.push('| Pertes | 70 | S37 PASS soft. |')
lines.push('| Consequences eco | 78 | champs ravagees (S39). |')
lines.push('| Demographiques | 74 | migration (S38). |')
lines.push('| Politiques | 80 | legitimacy. |')
lines.push('| Culturelles | 64 | soft. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[8].note}**`)
lines.push('')

lines.push('# 10. MONDE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Terrain | 80 | grid biomes. |')
lines.push('| Ressources | 82 | deposits/trees. |')
lines.push('| Montagnes | 78 | dig/mines. |')
lines.push('| Rivieres | 72 | shore/ports soft. |')
lines.push('| Forets | 80 | wood. |')
lines.push('| Agriculture | 68 | fields soft (hasField rare). |')
lines.push('| Mines | 82 | S11/S42. |')
lines.push('| Climat | 74 | seasons/temp. |')
lines.push('| Transport | 76 | roads/boats. |')
lines.push('| Distance | 74 | path costs. |')
lines.push('| Geo?societe | 80 | mine/road/port attract. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[9].note}**`)
lines.push('')

lines.push('# 11. VILLES')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Maisons | 78 | buildHouse. |')
lines.push('| Taille | 62 | richHomes S7 PARTIAL. |')
lines.push('| Qualite | 58 | soft. |')
lines.push('| Durabilite | 55 | soft. |')
lines.push('| Reparation | 60 | maintain_commons. |')
lines.push('| Croissance | 82 | camps?kingdom (S44). |')
lines.push('| Specialisation spatiale | 64 | S45 PARTIAL. |')
lines.push('| Densification | 72 | S47. |')
lines.push('| Routes | 84 | S13/S48. |')
lines.push('| Marches | 82 | S14. |')
lines.push('| Ports | 58 | ports=0 souvent ; barques log. |')
lines.push('| Fortifications | 84 | S35. |')
lines.push('| Ruines/cicatrices | 66 | battle scars P?L. |')
lines.push('| Infrastructure | 76 | mills/bridges. |')
lines.push('| Planification | 60 | soft planner. |')
lines.push('| Esthetique locale | 68 | culture culture. |')
lines.push('| Evolution long terme | 70 | stages. |')
lines.push('| Lisibilite sans UI | 62 | washes soft. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[10].note}**`)
lines.push('')

lines.push('# 12. HISTOIRE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Chronique | 88 | logCause dense. |')
lines.push('| Causalite explicite | 86 | cause?effet. |')
lines.push('| Memoire collective | 70 | rumours/circles. |')
lines.push('| Evenements | 80 | coups/wars/mines. |')
lines.push('| Continuite | 74 | milestones. |')
lines.push('| Contrefactuel | 62 | butterfly diverge. |')
lines.push('| Attribution | 72 | metrics. |')
lines.push('| Explicabilite UI | 68 | panels. |')
lines.push('| Narration emergeante | 76 | chronicles. |')
lines.push('| Longue duree | 58 | S50 FAIL (pas de centuries). |')
lines.push('| Cycles crise/rebuild | 72 | societyCycle. |')
lines.push('| Path dependence | 74 | multi-seed. |')
lines.push('| Fausse emergence | 70 | penality: dayGate soft wars. |')
lines.push('| Tracabilite | 80 | log ring. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[11].note}**`)
lines.push('')

lines.push('# 13. EMERGENCE GLOBALE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Chaines causales longues | 78 | war?fields?famine risk. |')
lines.push('| Interconnexion | 80 | eco?pol?war. |')
lines.push('| Multi-seed | 84 | butterfly PASS. |')
lines.push('| Non-scripted | 76 | peines: dayGate bandits/wars. |')
lines.push('| Surprises coherentes | 74 | alliances/coups. |')
lines.push('| Echelle societale | 72 | kingdom emerge. |')
lines.push('| Test ultime multi-sim | 68 | 42/50 scenarios ; S50 manque. |')
lines.push('| Absence omniscience | 70 | partial. |')
lines.push('| Boucles feedback | 78 | prices/jobs/war. |')
lines.push('| Robustesse | 74 | soakCore. |')
lines.push('| Densite evenements | 80 | mid-soak rich. |')
lines.push('| Lisibilite emergence | 72 | chronicle. |')
lines.push('| Fausse teleologie | 65 | penality kingdom soft. |')
lines.push('| Variete trajectoires | 76 | s1 vs s7. |')
lines.push('| Profondeur | 70 | mid-civ ; pas late-civ. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[12].note}**`)
lines.push('')

lines.push('# 14. VISUEL')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| Terrain lisible | 72 | nature engine. |')
lines.push('| Eau continue | 58 | encore risque etang. |')
lines.push('| Houppiers | 60 | overflow partiel. |')
lines.push('| Anti-tampon MC | 62 | regle active mais imperfect. |')
lines.push('| Props apres sol | 74 | z-order. |')
lines.push('| Activite PNJ | 70 | flecks P?L. |')
lines.push('| Guerre visuelle | 68 | battle scars. |')
lines.push('| Objets au sol | 64 | groundItems LOOT. |')
lines.push('| Societe sans UI | 60 | washes soft. |')
lines.push('| LOD micro/macro | 66 | civBlobs. |')
lines.push('| Assets ??64?76 | 55 | principal gap Visuel. |')
lines.push('| Coherence style | 68 | mix packs. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[13].note}**`)
lines.push('')

lines.push('# 15. PERFORMANCE')
lines.push('')
lines.push('| Critere | Note |')
lines.push('|--------|-----:|')
lines.push('| TPS @~36 | 88 | ~21?33ms historic ; atlas TPS?80. |')
lines.push('| TPS @100 | 82 | preuve ATLAS_V1_TPS 82.8?100.9. |')
lines.push('| TPS @500 | 55 | non mesure frais. |')
lines.push('| TPS @1000 | 45 | non mesure frais. |')
lines.push('| TPS @5000 | 30 | non mesure. |')
lines.push('| Determinisme | 90 | same-seed PASS. |')
lines.push('| Memoire | 70 | soft. |')
lines.push('| Worker | 72 | sim.worker present. |')
lines.push('| Budgets LOD | 74 | perfBudget. |')
lines.push('| Stutter | 68 | soft. |')
lines.push('| Scalabilite algorithmique | 60 | O(n?) relations risk. |')
lines.push('| Headless probes | 88 | harness solide. |')
lines.push('| CI tests | 80 | vitest determinism/mining. |')
lines.push('')
lines.push(`**Moyenne matiere : ${matieres[14].note}**`)
lines.push('')
lines.push('---')
lines.push('')
lines.push('# TOP 10 PROBLEMES')
lines.push('')
lines.push('1. **Herder/weaver quasi absents** malgre moutons (S9/S10 FAIL) ? textile demand insuffisante vs farmer lock.')
lines.push('2. **Credit/prets non observes** en soak (S20 FAIL) malgre wiring.')
lines.push('3. **Pas de multi-generation / kids** sur 35j (S50 FAIL) ? demographie trop lente.')
lines.push('4. **Assets nature ??64?76** encore PARTIAL (eau/houppiers/anti-MC).')
lines.push('5. **Grandes demeures riches** rares (S7 PARTIAL).')
lines.push('6. **Schismes religieux** rares (S24 PARTIAL).')
lines.push('7. **Quartiers specialises** peu lisibles (S45 PARTIAL).')
lines.push('8. **Perf non prouvee ?500 PNJ**.')
lines.push('9. **Perception/omniscience** encore trop forte sur hubs.')
lines.push('10. **Ports=0** frequents ; chaine portuaire soft.')
lines.push('')
lines.push('# TOP 10 POINTS FORTS')
lines.push('')
lines.push('1. **Chronique causale** logCause dense et lisible.')
lines.push('2. **Guerres emergentes** + paix trop couteuse (S33/S40).')
lines.push('3. **Alliances vs troisieme** (S34) apres fix causal.')
lines.push('4. **Coups / succession** mid-soak (S30?32).')
lines.push('5. **Marches / sells / firms / faillites** (S8/S14/S19).')
lines.push('6. **Mines + routes + royaumes** (S11/S13/S44).')
lines.push('7. **Migration / desertion** sous pression (S3/S38).')
lines.push('8. **Mariage = alliance familles** (S4).')
lines.push('9. **Butterfly + TPS?80** preuves atlas.')
lines.push('10. **Institutions + normes** depuis problemes (S28/S29).')
lines.push('')
lines.push('# DIAGNOSTIC FINAL')
lines.push('')
lines.push('1. La sim est-elle une civilisation emergente ou une collection de systemes ? **Hybride avance** ? interconnexion forte eco/pol/war ; textile/credit/demographie encore trous.')
lines.push('2. Les PNJ sont-ils des agents ou des pions ? **Agents partiels** (cerveau soft + HARD survival).')
lines.push('3. L\'economie forme-t-elle des prix/jobs reels ? **Oui mid-game** (prix, sells, firms) ; credit FAIL.')
lines.push('4. La politique emerge-t-elle ? **Oui** (polities, coups, normes).')
lines.push('5. La religion est-elle decorative ? **Non** (creeds/rites) mais schisme rare.')
lines.push('6. Les guerres ont-elles des causes ? **Oui** (scarcity/territory/rivalry).')
lines.push('7. Le monde contraint-il la societe ? **Oui** (mines/routes/moutons sous-exploites).')
lines.push('8. L\'histoire est-elle explicable ? **Oui** via chronique.')
lines.push('9. L\'emergence est-elle fausse ? **Partiellement** (quelques dayGates) mais majorite causale.')
lines.push('10. Le visuel sert-il la lecture societe ? **Partiel** ? assets nature restent le frein.')
lines.push('11. La perf tient-elle a l\'echelle cible ? **Oui ?100** ; **non prouve ?500**.')
lines.push('12. Que manque-t-il pour 90+ matieres ? **Demographie multi-gen, textile live, credit observe, assets nature, schismes.**')
lines.push('13. Que manque-t-il pour moyenne 100 ? **Tout le reste + zero faux PASS ? impossible sans mensonge aujourdhui.**')
lines.push('14. Prochain plus gros levier ? **Career mobility herder/weaver + naissance/enfants + nature render.**')
lines.push('15. Verdict global ? **Early?mid civ jouable et causalement riche ; pas encore civilisation profonde.**')
lines.push('')
lines.push('# PRIORITES D\'AMELIORATION')
lines.push('')
lines.push('P1 ? Debloquer **herder/weaver** sous pression laine (S9/S10) sans cheat food.')
lines.push('P2 ? Faire **vivre le credit** (S20) avec preuves multi-seed.')
lines.push('P3 ? **Demographie** : naissances/enfants observables ?60?90j (S50).')
lines.push('P4 ? **Nature visuelle** ??64?76 : eau continue, houppiers overflow, anti tampon MC.')
lines.push('P5 ? **Maisons riches / densite / quartiers** (S7/S45/S47).')
lines.push('P6 ? **Schismes** plus frequents sous tension creed (S24).')
lines.push('P7 ? **Perf soak** 500/1000 PNJ mesures TPS.')
lines.push('P8 ? **Ports** causaux depuis echanges cotiers.')
lines.push('P9 ? Reduire omniscience hub / dayGates restants.')
lines.push('P10 ? Re-probe scenarios jusqu\'a ?48/50 PASS sans inflation.')
lines.push('')
lines.push('---')
lines.push('')
lines.push('*Bulletin severe ? pas de moyenne 100 declaree. Preuves : ATLAS_V1_SCENARIO_MATRIX.md, SIMULATION_ATLAS_V1_SCORECARD.md, ATLAS_V1_*_PROOF*.*')
lines.push('')

fs.writeFileSync(path, lines.join('\n'), 'utf8')
console.log('wrote', path, 'moyenne', mg.toFixed(1))
