import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
const t = fs.readFileSync(p, "utf8")
const a = t.indexOf("let _shoreTmp")
const a2 = a >= 0 ? a : t.indexOf("export function paintViewportShoreStrip")
if (a2 < 0) throw new Error("no strip marker")

const rest = [
  "let _shoreTmp: HTMLCanvasElement | null = null",
  "function shoreTmpCanvas(w: number, h: number): CanvasRenderingContext2D {",
  "  if (!_shoreTmp || _shoreTmp.width < w || _shoreTmp.height < h) {",
  "    _shoreTmp = document.createElement(\"canvas\")",
  "    _shoreTmp.width = Math.max(w, 64)",
  "    _shoreTmp.height = Math.max(h, 64)",
  "  } else if (_shoreTmp.width < w || _shoreTmp.height < h) {",
  "    _shoreTmp.width = w",
  "    _shoreTmp.height = h",
  "  }",
  "  return _shoreTmp.getContext(\"2d\")!",
  "}",
  "",
  "function cellTouchesOpposite(",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  gx: number,",
  "  gy: number,",
  "  wantWater: boolean,",
  "  r: number,",
  "): boolean {",
  "  for (let dy = -r; dy <= r; dy++) {",
  "    for (let dx = -r; dx <= r; dx++) {",
  "      if (dx === 0 && dy === 0) continue",
  "      const x = gx + dx",
  "      const y = gy + dy",
  "      if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "      if ((terrain[y * worldW + x] === WATER) === wantWater) return true",
  "    }",
  "  }",
  "  return false",
  "}",
  "",
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "",
  "  // 1) Shore AABB only — skip inland/deep ocean for FPS.",
  "  let bx0 = x1",
  "  let by0 = y1",
  "  let bx1 = x0",
  "  let by1 = y0",
  "  let bandN = 0",
  "  const band = new Uint8Array(Math.max(0, (x1 - x0) * (y1 - y0)))",
  "  const bw = x1 - x0",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      const hereW = terrain[gy * worldW + gx]! === WATER",
  "      const hit = cellTouchesOpposite(terrain, worldW, gx, gy, !hereW, 3)",
  "      if (!hit) continue",
  "      band[(gy - y0) * bw + (gx - x0)] = 1",
  "      bandN++",
  "      if (gx < bx0) bx0 = gx",
  "      if (gy < by0) by0 = gy",
  "      if (gx + 1 > bx1) bx1 = gx + 1",
  "      if (gy + 1 > by1) by1 = gy + 1",
  "    }",
  "  }",
  "  if (bandN === 0) return",
  "  // Pad AABB one cell so overspill covers stairs.",
  "  bx0 = Math.max(x0, bx0 - 1)",
  "  by0 = Math.max(y0, by0 - 1)",
  "  bx1 = Math.min(x1, bx1 + 1)",
  "  by1 = Math.min(y1, by1 + 1)",
  "",
  "  const px0 = (bx0 * tilePx - camX) * zoom",
  "  const py0 = (by0 * tilePx - camY) * zoom",
  "  const pw = Math.max(4, Math.ceil((bx1 - bx0) * tileS))",
  "  const ph = Math.max(4, Math.ceil((by1 - by0) * tileS))",
  "  // Dense but capped: prefer ~4–6 samples/tile edge, max ~280px buffer.",
  "  const cellsX = Math.max(1, bx1 - bx0)",
  "  const cellsY = Math.max(1, by1 - by0)",
  "  const target = Math.min(280, Math.max(64, Math.round(Math.sqrt(cellsX * cellsY) * 18)))",
  "  const dw = Math.max(48, Math.min(target, Math.round(cellsX * 6)))",
  "  const dh = Math.max(48, Math.min(target, Math.round(cellsY * 6)))",
  "  const img = ctx.createImageData(dw, dh)",
  "  const data = img.data",
  "",
  "  const sandNearCell = (ix: number, iy: number): boolean => {",
  "    for (let dy = -2; dy <= 2; dy++) {",
  "      for (let dx = -2; dx <= 2; dx++) {",
  "        const x = ix + dx",
  "        const y = iy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (terrain[y * worldW + x] === SAND) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "",
  "  try {",
  "    for (let j = 0; j < dh; j++) {",
  "      const wy = by0 + ((j + 0.5) / dh) * (by1 - by0)",
  "      const iy = Math.floor(wy)",
  "      for (let i = 0; i < dw; i++) {",
  "        const wx = bx0 + ((i + 0.5) / dw) * (bx1 - bx0)",
  "        const ix = Math.floor(wx)",
  "        const o = (j * dw + i) * 4",
  "        // Cheap band test via precomputed cell mask (neighbors too).",
  "        let on = false",
  "        for (let dy = -1; dy <= 1 && !on; dy++) {",
  "          for (let dx = -1; dx <= 1; dx++) {",
  "            const cx = ix + dx",
  "            const cy = iy + dy",
  "            if (cx < x0 || cy < y0 || cx >= x1 || cy >= y1) continue",
  "            if (band[(cy - y0) * bw + (cx - x0)]) {",
  "              on = true",
  "              break",
  "            }",
  "          }",
  "        }",
  "        if (!on) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        const f = shoreField(terrain, worldW, wx, wy)",
  "        const tint = simplex2(wx * 2.05, wy * 2.05) * 4",
  "        const useSand = sandNearCell(ix, iy)",
  "        let r: number, g: number, b: number",
  "        if (useSand) {",
  "          const wSand = smoothstep(0.04, 0.36, f)",
  "          const wWater = smoothstep(0.3, 0.6, f)",
  "          const wDeep = smoothstep(0.52, 0.9, f)",
  "          const r1 = land[0] * (1 - wSand) + sand[0] * wSand",
  "          const g1 = land[1] * (1 - wSand) + sand[1] * wSand",
  "          const b1 = land[2] * (1 - wSand) + sand[2] * wSand",
  "          const r2 = r1 * (1 - wWater) + water[0] * wWater",
  "          const g2 = g1 * (1 - wWater) + water[1] * wWater",
  "          const b2 = b1 * (1 - wWater) + water[2] * wWater",
  "          r = r2 * (1 - wDeep) + deep[0] * wDeep + tint",
  "          g = g2 * (1 - wDeep) + deep[1] * wDeep + tint * 0.7",
  "          b = b2 * (1 - wDeep) + deep[2] * wDeep + tint * 0.45",
  "        } else {",
  "          const w1 = smoothstep(0.02, 0.5, f)",
  "          const w2 = smoothstep(0.45, 0.9, f)",
  "          const r0 = land[0] * (1 - w1) + water[0] * w1",
  "          const g0 = land[1] * (1 - w1) + water[1] * w1",
  "          const b0 = land[2] * (1 - w1) + water[2] * w1",
  "          r = r0 * (1 - w2) + deep[0] * w2 + tint",
  "          g = g0 * (1 - w2) + deep[1] * w2 + tint * 0.7",
  "          b = b0 * (1 - w2) + deep[2] * w2 + tint * 0.45",
  "        }",
  "        // Opaque overwrite — covers world-buffer Manhattan stairs.",
  "        data[o] = Math.max(0, Math.min(255, r | 0))",
  "        data[o + 1] = Math.max(0, Math.min(255, g | 0))",
  "        data[o + 2] = Math.max(0, Math.min(255, b | 0))",
  "        data[o + 3] = 255",
  "      }",
  "    }",
  "    const tctx = shoreTmpCanvas(dw, dh)",
  "    tctx.clearRect(0, 0, dw, dh)",
  "    tctx.putImageData(img, 0, 0)",
  "    const prev = ctx.imageSmoothingEnabled",
  "    ctx.imageSmoothingEnabled = true",
  "    ctx.globalAlpha = 1",
  "    ctx.drawImage(_shoreTmp!, 0, 0, dw, dh, px0, py0, pw, ph)",
  "    ctx.imageSmoothingEnabled = prev",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "",
  "  let bx0 = x1",
  "  let by0 = y1",
  "  let bx1 = x0",
  "  let by1 = y0",
  "  let n = 0",
  "  const mark = new Uint8Array(Math.max(0, (x1 - x0) * (y1 - y0)))",
  "  const bw = x1 - x0",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      let near = false",
  "      for (let dy = -2; dy <= 2 && !near; dy++) {",
  "        for (let dx = -2; dx <= 2; dx++) {",
  "          const x = gx + dx",
  "          const y = gy + dy",
  "          if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "          if (isDirtOrSand(terrain[y * worldW + x]!)) {",
  "            near = true",
  "            break",
  "          }",
  "        }",
  "      }",
  "      if (!near) continue",
  "      mark[(gy - y0) * bw + (gx - x0)] = 1",
  "      n++",
  "      if (gx < bx0) bx0 = gx",
  "      if (gy < by0) by0 = gy",
  "      if (gx + 1 > bx1) bx1 = gx + 1",
  "      if (gy + 1 > by1) by1 = gy + 1",
  "    }",
  "  }",
  "  if (n === 0) return",
  "  bx0 = Math.max(x0, bx0 - 1)",
  "  by0 = Math.max(y0, by0 - 1)",
  "  bx1 = Math.min(x1, bx1 + 1)",
  "  by1 = Math.min(y1, by1 + 1)",
  "",
  "  const px0 = (bx0 * tilePx - camX) * zoom",
  "  const py0 = (by0 * tilePx - camY) * zoom",
  "  const pw = Math.max(4, Math.ceil((bx1 - bx0) * tileS))",
  "  const ph = Math.max(4, Math.ceil((by1 - by0) * tileS))",
  "  const cellsX = Math.max(1, bx1 - bx0)",
  "  const cellsY = Math.max(1, by1 - by0)",
  "  const target = Math.min(240, Math.max(48, Math.round(Math.sqrt(cellsX * cellsY) * 16)))",
  "  const dw = Math.max(40, Math.min(target, Math.round(cellsX * 5)))",
  "  const dh = Math.max(40, Math.min(target, Math.round(cellsY * 5)))",
  "  const img = ctx.createImageData(dw, dh)",
  "  const data = img.data",
  "",
  "  try {",
  "    for (let j = 0; j < dh; j++) {",
  "      const wy = by0 + ((j + 0.5) / dh) * (by1 - by0)",
  "      const iy = Math.floor(wy)",
  "      for (let i = 0; i < dw; i++) {",
  "        const wx = bx0 + ((i + 0.5) / dw) * (bx1 - bx0)",
  "        const ix = Math.floor(wx)",
  "        const o = (j * dw + i) * 4",
  "        let on = false",
  "        for (let dy = -1; dy <= 1 && !on; dy++) {",
  "          for (let dx = -1; dx <= 1; dx++) {",
  "            const cx = ix + dx",
  "            const cy = iy + dy",
  "            if (cx < x0 || cy < y0 || cx >= x1 || cy >= y1) continue",
  "            if (mark[(cy - y0) * bw + (cx - x0)]) {",
  "              on = true",
  "              break",
  "            }",
  "          }",
  "        }",
  "        if (!on) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        const f = dirtField(terrain, worldW, wx, wy)",
  "        const w = smoothstep(0.05, 0.52, f)",
  "        if (w < 0.04) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        let sandN = 0",
  "        for (let dy = -1; dy <= 1; dy++) {",
  "          for (let dx = -1; dx <= 1; dx++) {",
  "            const x = ix + dx",
  "            const y = iy + dy",
  "            if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "            if (terrain[y * worldW + x] === SAND) sandN++",
  "          }",
  "        }",
  "        const cover = sandN > 0 ? sand : dirtCol",
  "        const tint = simplex2(wx * 2.5, wy * 2.5) * 6",
  "        data[o] = Math.max(0, Math.min(255, (land[0] * (1 - w) + cover[0] * w + tint) | 0))",
  "        data[o + 1] = Math.max(0, Math.min(255, (land[1] * (1 - w) + cover[1] * w + tint * 0.7) | 0))",
  "        data[o + 2] = Math.max(0, Math.min(255, (land[2] * (1 - w) + cover[2] * w + tint * 0.45) | 0))",
  "        data[o + 3] = 255",
  "      }",
  "    }",
  "    const tctx = shoreTmpCanvas(dw, dh)",
  "    tctx.clearRect(0, 0, dw, dh)",
  "    tctx.putImageData(img, 0, 0)",
  "    const prev = ctx.imageSmoothingEnabled",
  "    ctx.imageSmoothingEnabled = true",
  "    ctx.globalAlpha = 1",
  "    ctx.drawImage(_shoreTmp!, 0, 0, dw, dh, px0, py0, pw, ph)",
  "    ctx.imageSmoothingEnabled = prev",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
].join("\n")

fs.writeFileSync(p, t.slice(0, a2) + rest, "utf8")
const out = fs.readFileSync(p, "utf8")
console.log({
  aabb: out.includes("Shore AABB only"),
  opaque: out.includes("Opaque overwrite"),
  size: out.length,
})
