import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
let t = fs.readFileSync(p, "utf8")

// Ensure strong warp still present
if (!t.includes("* 2.15")) {
  t = t.replace(
    "const warp = shoreWarp(wx * 0.55, wy * 0.55) * 1.45\n  const warpY = shoreWarp(wy * 0.55 + 6.1, wx * 0.55) * 1.45",
    "const warp = shoreWarp(wx * 0.4, wy * 0.4) * 2.4\n  const warpY = shoreWarp(wy * 0.4 + 6.1, wx * 0.4) * 2.4",
  )
} else {
  t = t.replace("* 2.15", "* 2.55")
}

const a = t.indexOf("export function paintViewportShoreStrip")
if (a < 0) throw new Error("no strip")

const rest = [
  "let _shoreTmp: HTMLCanvasElement | null = null",
  "function shoreTmpCanvas(dim: number): CanvasRenderingContext2D {",
  "  if (!_shoreTmp || _shoreTmp.width < dim || _shoreTmp.height < dim) {",
  "    _shoreTmp = document.createElement(\"canvas\")",
  "    _shoreTmp.width = dim",
  "    _shoreTmp.height = dim",
  "  }",
  "  return _shoreTmp.getContext(\"2d\")!",
  "}",
  "",
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "  const PAD = 1.05",
  "  const span = 1 + PAD * 2",
  "  // Cap cost: ~36 samples/side keeps FPS while crossing cell seams.",
  "  const dim = Math.max(28, Math.min(48, Math.round(tileS * 0.22)))",
  "  const inBand = (gx: number, gy: number): boolean => {",
  "    const hereW = terrain[gy * worldW + gx]! === WATER",
  "    for (let dy = -4; dy <= 4; dy++) {",
  "      for (let dx = -4; dx <= 4; dx++) {",
  "        if (dx === 0 && dy === 0) continue",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if ((terrain[y * worldW + x] === WATER) !== hereW) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  const hasSandNear = (gx: number, gy: number): boolean => {",
  "    for (let dy = -2; dy <= 2; dy++) {",
  "      for (let dx = -2; dx <= 2; dx++) {",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (terrain[y * worldW + x] === SAND) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  try {",
  "    for (let gy = y0; gy < y1; gy++) {",
  "      for (let gx = x0; gx < x1; gx++) {",
  "        if (!inBand(gx, gy)) continue",
  "        const useSand = hasSandNear(gx, gy)",
  "        const img = ctx.createImageData(dim, dim)",
  "        const data = img.data",
  "        for (let j = 0; j < dim; j++) {",
  "          const wy = gy - PAD + ((j + 0.5) / dim) * span",
  "          for (let i = 0; i < dim; i++) {",
  "            const wx = gx - PAD + ((i + 0.5) / dim) * span",
  "            const f = shoreField(terrain, worldW, wx, wy)",
  "            const tint = simplex2(wx * 2.05, wy * 2.05) * 4",
  "            let r: number, g: number, b: number",
  "            if (useSand) {",
  "              const wSand = smoothstep(0.05, 0.38, f)",
  "              const wWater = smoothstep(0.32, 0.62, f)",
  "              const wDeep = smoothstep(0.55, 0.92, f)",
  "              const r1 = land[0] * (1 - wSand) + sand[0] * wSand",
  "              const g1 = land[1] * (1 - wSand) + sand[1] * wSand",
  "              const b1 = land[2] * (1 - wSand) + sand[2] * wSand",
  "              const r2 = r1 * (1 - wWater) + water[0] * wWater",
  "              const g2 = g1 * (1 - wWater) + water[1] * wWater",
  "              const b2 = b1 * (1 - wWater) + water[2] * wWater",
  "              r = r2 * (1 - wDeep) + deep[0] * wDeep + tint",
  "              g = g2 * (1 - wDeep) + deep[1] * wDeep + tint * 0.7",
  "              b = b2 * (1 - wDeep) + deep[2] * wDeep + tint * 0.45",
  "            } else {",
  "              const w1 = smoothstep(0.02, 0.5, f)",
  "              const w2 = smoothstep(0.45, 0.9, f)",
  "              const r0 = land[0] * (1 - w1) + water[0] * w1",
  "              const g0 = land[1] * (1 - w1) + water[1] * w1",
  "              const b0 = land[2] * (1 - w1) + water[2] * w1",
  "              r = r0 * (1 - w2) + deep[0] * w2 + tint",
  "              g = g0 * (1 - w2) + deep[1] * w2 + tint * 0.7",
  "              b = b0 * (1 - w2) + deep[2] * w2 + tint * 0.45",
  "            }",
  "            const o = (j * dim + i) * 4",
  "            data[o] = Math.max(0, Math.min(255, r | 0))",
  "            data[o + 1] = Math.max(0, Math.min(255, g | 0))",
  "            data[o + 2] = Math.max(0, Math.min(255, b | 0))",
  "            data[o + 3] = 255",
  "          }",
  "        }",
  "        const tctx = shoreTmpCanvas(dim)",
  "        tctx.putImageData(img, 0, 0)",
  "        const px = (gx * tilePx - camX) * zoom - PAD * tileS",
  "        const py = (gy * tilePx - camY) * zoom - PAD * tileS",
  "        const prev = ctx.imageSmoothingEnabled",
  "        ctx.imageSmoothingEnabled = true",
  "        ctx.drawImage(_shoreTmp!, 0, 0, dim, dim, px, py, tileS * span, tileS * span)",
  "        ctx.imageSmoothingEnabled = prev",
  "      }",
  "    }",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "  const PAD = 1.0",
  "  const span = 1 + PAD * 2",
  "  const dim = Math.max(24, Math.min(44, Math.round(tileS * 0.2)))",
  "  const nearDirt = (gx: number, gy: number): boolean => {",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (isDirtOrSand(terrain[y * worldW + x]!)) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  try {",
  "    for (let gy = y0; gy < y1; gy++) {",
  "      for (let gx = x0; gx < x1; gx++) {",
  "        if (!nearDirt(gx, gy)) continue",
  "        let sandN = 0",
  "        for (let dy = -1; dy <= 1; dy++) {",
  "          for (let dx = -1; dx <= 1; dx++) {",
  "            const x = gx + dx",
  "            const y = gy + dy",
  "            if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "            if (terrain[y * worldW + x] === SAND) sandN++",
  "          }",
  "        }",
  "        const cover = sandN > 0 || terrain[gy * worldW + gx] === SAND ? sand : dirtCol",
  "        const img = ctx.createImageData(dim, dim)",
  "        const data = img.data",
  "        for (let j = 0; j < dim; j++) {",
  "          const wy = gy - PAD + ((j + 0.5) / dim) * span",
  "          for (let i = 0; i < dim; i++) {",
  "            const wx = gx - PAD + ((i + 0.5) / dim) * span",
  "            const f = dirtField(terrain, worldW, wx, wy)",
  "            const w = smoothstep(0.05, 0.52, f)",
  "            const tint = simplex2(wx * 2.5, wy * 2.5) * 6",
  "            const o = (j * dim + i) * 4",
  "            data[o] = Math.max(0, Math.min(255, (land[0] * (1 - w) + cover[0] * w + tint) | 0))",
  "            data[o + 1] = Math.max(0, Math.min(255, (land[1] * (1 - w) + cover[1] * w + tint * 0.7) | 0))",
  "            data[o + 2] = Math.max(0, Math.min(255, (land[2] * (1 - w) + cover[2] * w + tint * 0.45) | 0))",
  "            data[o + 3] = w < 0.03 ? 0 : 255",
  "          }",
  "        }",
  "        const tctx = shoreTmpCanvas(dim)",
  "        tctx.putImageData(img, 0, 0)",
  "        const px = (gx * tilePx - camX) * zoom - PAD * tileS",
  "        const py = (gy * tilePx - camY) * zoom - PAD * tileS",
  "        const prev = ctx.imageSmoothingEnabled",
  "        ctx.imageSmoothingEnabled = true",
  "        ctx.drawImage(_shoreTmp!, 0, 0, dim, dim, px, py, tileS * span, tileS * span)",
  "        ctx.imageSmoothingEnabled = prev",
  "      }",
  "    }",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
].join("\n")

fs.writeFileSync(p, t.slice(0, a) + rest, "utf8")
console.log("patched", fs.readFileSync(p, "utf8").includes("shoreTmpCanvas"), fs.readFileSync(p, "utf8").includes("* 2.55"))
