import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
let t = fs.readFileSync(p, "utf8")

t = t.replace(
  "return signed * 0.65 + (bil - 0.5) * 0.5 + (blob - 0.5) * 0.55 + shoreWarp(sx + 2.4, sy + 1.1) * 0.28",
  "return signed * 0.5 + (bil - 0.5) * 0.3 + (blob - 0.5) * 1.2 + shoreWarp(sx + 2.4, sy + 1.1) * 0.5",
)

const a = t.indexOf("export function paintViewportShoreStrip")
const b = t.indexOf("export function paintViewportDirtStrip")
if (a < 0 || b < 0) throw new Error("markers missing")

const shore = [
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "  const field = (wx: number, wy: number) => shoreField(terrain, worldW, wx, wy)",
  "  const PAD = 1.4",
  "",
  "  const nearCoast = (gx: number, gy: number): boolean => {",
  "    const cell = terrain[gy * worldW + gx]!",
  "    let waterN = 0",
  "    let landN = 0",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        if (dx === 0 && dy === 0) continue",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (terrain[y * worldW + x] === WATER) waterN++",
  "        else landN++",
  "      }",
  "    }",
  "    if (cell === WATER) return landN >= 1",
  "    return waterN >= 1",
  "  }",
  "",
  "  // Every near-coast cell + large overspill — shared SDF crosses grid seams.",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!nearCoast(gx, gy)) continue",
  "      const px = (gx * tilePx - camX) * zoom",
  "      const py = (gy * tilePx - camY) * zoom",
  "      paintOpaqueLerpStrip(",
  "        ctx, field, gx, gy, px, py, tileS, land, water, 0.05, 0.58, PAD,",
  "        (wx, wy) => simplex2(wx * 2.1, wy * 2.1) * 5,",
  "      )",
  "      paintOpaqueLerpStrip(",
  "        ctx, field, gx, gy, px, py, tileS, water, deep, 0.48, 0.95, PAD,",
  "        undefined, 0.38, 1.05,",
  "      )",
  "    }",
  "  }",
  "}",
  "",
  "",
].join("\n")

const dirt = [
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "  const field = (wx: number, wy: number) => dirtField(terrain, worldW, wx, wy)",
  "  const PAD = 1.3",
  "",
  "  const nearDirt = (gx: number, gy: number): boolean => {",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (isDirtOrSand(terrain[y * worldW + x]!)) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!nearDirt(gx, gy)) continue",
  "      const px = (gx * tilePx - camX) * zoom",
  "      const py = (gy * tilePx - camY) * zoom",
  "      const cell = terrain[gy * worldW + gx]!",
  "      const cover = cell === SAND ? sand : dirtCol",
  "      paintOpaqueLerpStrip(",
  "        ctx, field, gx, gy, px, py, tileS, land, cover, 0.06, 0.6, PAD,",
  "        (wx, wy) => simplex2(wx * 2.6, wy * 2.6) * 7,",
  "      )",
  "    }",
  "  }",
  "}",
  "",
].join("\n")

t = t.slice(0, a) + shore + dirt
fs.writeFileSync(p, t, "utf8")
const check = fs.readFileSync(p, "utf8")
console.log({
  noChecker: !check.includes("(gx + gy) & 1"),
  pad14: check.includes("PAD = 1.4"),
  pad13: check.includes("PAD = 1.3"),
  blob: check.includes("(blob - 0.5) * 1.2"),
  size: check.length,
})
