import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
let t = fs.readFileSync(p, "utf8")
const a = t.indexOf("export function paintViewportShoreStrip")
if (a < 0) throw new Error("missing strip")

const rest = [
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "  // Full-cell continuous raster on the shore band — never leave Manhattan underlay gaps.",
  "  const step = Math.max(1.05, Math.min(2.8, tileS / 12))",
  "  const PAD = 0.72",
  "  const inBand = (gx: number, gy: number): boolean => {",
  "    const here = terrain[gy * worldW + gx]!",
  "    const hereW = here === WATER",
  "    for (let dy = -4; dy <= 4; dy++) {",
  "      for (let dx = -4; dx <= 4; dx++) {",
  "        if (dx === 0 && dy === 0) continue",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        const w = terrain[y * worldW + x] === WATER",
  "        if (w !== hereW) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  ctx.globalAlpha = 1",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!inBand(gx, gy)) continue",
  "      const px0 = (gx * tilePx - camX) * zoom",
  "      const py0 = (gy * tilePx - camY) * zoom",
  "      const xStart = -PAD * tileS",
  "      const yStart = -PAD * tileS",
  "      const xEnd = tileS + PAD * tileS",
  "      const yEnd = tileS + PAD * tileS",
  "      for (let oy = yStart; oy < yEnd; oy += step) {",
  "        for (let ox = xStart; ox < xEnd; ox += step) {",
  "          const wx = gx + (ox + step * 0.5) / tileS",
  "          const wy = gy + (oy + step * 0.5) / tileS",
  "          const f = shoreField(terrain, worldW, wx, wy)",
  "          const w1 = smoothstep(0.02, 0.52, f)",
  "          const w2 = smoothstep(0.45, 0.9, f)",
  "          const r0 = land[0] * (1 - w1) + water[0] * w1",
  "          const g0 = land[1] * (1 - w1) + water[1] * w1",
  "          const b0 = land[2] * (1 - w1) + water[2] * w1",
  "          const tint = simplex2(wx * 2.05, wy * 2.05) * 5",
  "          const r = Math.max(0, Math.min(255, (r0 * (1 - w2) + deep[0] * w2 + tint) | 0))",
  "          const g = Math.max(0, Math.min(255, (g0 * (1 - w2) + deep[1] * w2 + tint * 0.7) | 0))",
  "          const b = Math.max(0, Math.min(255, (b0 * (1 - w2) + deep[2] * w2 + tint * 0.45) | 0))",
  '          ctx.fillStyle = "rgb(" + r + "," + g + "," + b + ")"',
  "          ctx.fillRect(px0 + ox - 0.25, py0 + oy - 0.25, step + 0.7, step + 0.7)",
  "        }",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "  const step = Math.max(1.05, Math.min(2.8, tileS / 12))",
  "  const PAD = 0.7",
  "  const nearDirt = (gx: number, gy: number): boolean => {",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (isDirtOrSand(terrain[y * worldW + x]!)) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  ctx.globalAlpha = 1",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!nearDirt(gx, gy)) continue",
  "      const px0 = (gx * tilePx - camX) * zoom",
  "      const py0 = (gy * tilePx - camY) * zoom",
  "      const cell = terrain[gy * worldW + gx]!",
  "      // Prefer sand tone when any sand in neighborhood, else dirt.",
  "      let sandN = 0",
  "      for (let dy = -1; dy <= 1; dy++) {",
  "        for (let dx = -1; dx <= 1; dx++) {",
  "          const x = gx + dx",
  "          const y = gy + dy",
  "          if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "          if (terrain[y * worldW + x] === SAND) sandN++",
  "        }",
  "      }",
  "      const cover = sandN > 0 || cell === SAND ? sand : dirtCol",
  "      for (let oy = -PAD * tileS; oy < tileS + PAD * tileS; oy += step) {",
  "        for (let ox = -PAD * tileS; ox < tileS + PAD * tileS; ox += step) {",
  "          const wx = gx + (ox + step * 0.5) / tileS",
  "          const wy = gy + (oy + step * 0.5) / tileS",
  "          const f = dirtField(terrain, worldW, wx, wy)",
  "          const w = smoothstep(0.04, 0.55, f)",
  "          const tint = simplex2(wx * 2.5, wy * 2.5) * 6",
  "          const r = Math.max(0, Math.min(255, (land[0] * (1 - w) + cover[0] * w + tint) | 0))",
  "          const g = Math.max(0, Math.min(255, (land[1] * (1 - w) + cover[1] * w + tint * 0.7) | 0))",
  "          const b = Math.max(0, Math.min(255, (land[2] * (1 - w) + cover[2] * w + tint * 0.45) | 0))",
  '          ctx.fillStyle = "rgb(" + r + "," + g + "," + b + ")"',
  "          ctx.fillRect(px0 + ox - 0.25, py0 + oy - 0.25, step + 0.7, step + 0.7)",
  "        }",
  "      }",
  "    }",
  "  }",
  "}",
  "",
].join("\n")

fs.writeFileSync(p, t.slice(0, a) + rest, "utf8")
console.log("ok", fs.readFileSync(p, "utf8").includes("never leave Manhattan"), fs.statSync(p).size)
