import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
let t = fs.readFileSync(p, "utf8")
const a = t.indexOf("let _shoreTmp")
const a2 = a >= 0 ? a : t.indexOf("export function paintViewportShoreStrip")
if (a2 < 0) throw new Error("no strip")

const rest = [
  "let _shoreTmp: HTMLCanvasElement | null = null",
  "function shoreTmpCanvas(w: number, h: number): CanvasRenderingContext2D {",
  "  if (!_shoreTmp || _shoreTmp.width < w || _shoreTmp.height < h) {",
  "    _shoreTmp = document.createElement(\"canvas\")",
  "    _shoreTmp.width = Math.max(w, _shoreTmp?.width ?? 0)",
  "    _shoreTmp.height = Math.max(h, _shoreTmp?.height ?? 0)",
  "  }",
  "  return _shoreTmp.getContext(\"2d\")!",
  "}",
  "",
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "  // One shared buffer for the whole view — kills per-cell ImageData mosaic seams.",
  "  const px0 = (x0 * tilePx - camX) * zoom",
  "  const py0 = (y0 * tilePx - camY) * zoom",
  "  const pw = Math.max(8, Math.ceil((x1 - x0) * tileS))",
  "  const ph = Math.max(8, Math.ceil((y1 - y0) * tileS))",
  "  // Cap resolution for FPS; scale up with smoothing.",
  "  const scale = Math.max(0.22, Math.min(0.55, 140 / Math.max(pw, ph)))",
  "  const dw = Math.max(32, Math.round(pw * scale))",
  "  const dh = Math.max(32, Math.round(ph * scale))",
  "  const img = ctx.createImageData(dw, dh)",
  "  const data = img.data",
  "  const hasSandNear = (gx: number, gy: number): boolean => {",
  "    const ix = gx | 0",
  "    const iy = gy | 0",
  "    for (let dy = -2; dy <= 2; dy++) {",
  "      for (let dx = -2; dx <= 2; dx++) {",
  "        const x = ix + dx",
  "        const y = iy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (terrain[y * worldW + x] === SAND) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  const inBand = (wx: number, wy: number): boolean => {",
  "    const ix = Math.floor(wx)",
  "    const iy = Math.floor(wy)",
  "    if (ix < 0 || iy < 0 || ix >= worldW || iy >= worldW) return false",
  "    const hereW = terrain[iy * worldW + ix]! === WATER",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = ix + dx",
  "        const y = iy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if ((terrain[y * worldW + x] === WATER) !== hereW) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  try {",
  "    for (let j = 0; j < dh; j++) {",
  "      const wy = y0 + ((j + 0.5) / dh) * (y1 - y0)",
  "      for (let i = 0; i < dw; i++) {",
  "        const wx = x0 + ((i + 0.5) / dw) * (x1 - x0)",
  "        const o = (j * dw + i) * 4",
  "        if (!inBand(wx, wy)) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        const f = shoreField(terrain, worldW, wx, wy)",
  "        const tint = simplex2(wx * 2.05, wy * 2.05) * 4",
  "        const useSand = hasSandNear(wx, wy)",
  "        let r: number, g: number, b: number",
  "        if (useSand) {",
  "          const wSand = smoothstep(0.05, 0.38, f)",
  "          const wWater = smoothstep(0.32, 0.62, f)",
  "          const wDeep = smoothstep(0.55, 0.92, f)",
  "          const r1 = land[0] * (1 - wSand) + sand[0] * wSand",
  "          const g1 = land[1] * (1 - wSand) + sand[1] * wSand",
  "          const b1 = land[2] * (1 - wSand) + sand[2] * wSand",
  "          const r2 = r1 * (1 - wWater) + water[0] * wWater",
  "          const g2 = g1 * (1 - wWater) + water[1] * wWater",
  "          const b2 = b1 * (1 - wWater) + water[2] * wWater",
  "          r = r2 * (1 - wDeep) + deep[0] * wDeep + tint",
  "          g = g2 * (1 - wDeep) + deep[1] * wDeep + tint * 0.7",
  "          b = b2 * (1 - wDeep) + deep[2] * wDeep + tint * 0.45",
  "        } else {",
  "          const w1 = smoothstep(0.02, 0.5, f)",
  "          const w2 = smoothstep(0.45, 0.9, f)",
  "          const r0 = land[0] * (1 - w1) + water[0] * w1",
  "          const g0 = land[1] * (1 - w1) + water[1] * w1",
  "          const b0 = land[2] * (1 - w1) + water[2] * w1",
  "          r = r0 * (1 - w2) + deep[0] * w2 + tint",
  "          g = g0 * (1 - w2) + deep[1] * w2 + tint * 0.7",
  "          b = b0 * (1 - w2) + deep[2] * w2 + tint * 0.45",
  "        }",
  "        data[o] = Math.max(0, Math.min(255, r | 0))",
  "        data[o + 1] = Math.max(0, Math.min(255, g | 0))",
  "        data[o + 2] = Math.max(0, Math.min(255, b | 0))",
  "        data[o + 3] = 255",
  "      }",
  "    }",
  "    const tctx = shoreTmpCanvas(dw, dh)",
  "    tctx.clearRect(0, 0, dw, dh)",
  "    tctx.putImageData(img, 0, 0)",
  "    const prev = ctx.imageSmoothingEnabled",
  "    ctx.imageSmoothingEnabled = true",
  "    ctx.drawImage(_shoreTmp!, 0, 0, dw, dh, px0, py0, pw, ph)",
  "    ctx.imageSmoothingEnabled = prev",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "  const px0 = (x0 * tilePx - camX) * zoom",
  "  const py0 = (y0 * tilePx - camY) * zoom",
  "  const pw = Math.max(8, Math.ceil((x1 - x0) * tileS))",
  "  const ph = Math.max(8, Math.ceil((y1 - y0) * tileS))",
  "  const scale = Math.max(0.22, Math.min(0.55, 140 / Math.max(pw, ph)))",
  "  const dw = Math.max(32, Math.round(pw * scale))",
  "  const dh = Math.max(32, Math.round(ph * scale))",
  "  const img = ctx.createImageData(dw, dh)",
  "  const data = img.data",
  "  const nearDirt = (wx: number, wy: number): boolean => {",
  "    const ix = Math.floor(wx)",
  "    const iy = Math.floor(wy)",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = ix + dx",
  "        const y = iy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (isDirtOrSand(terrain[y * worldW + x]!)) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  try {",
  "    for (let j = 0; j < dh; j++) {",
  "      const wy = y0 + ((j + 0.5) / dh) * (y1 - y0)",
  "      for (let i = 0; i < dw; i++) {",
  "        const wx = x0 + ((i + 0.5) / dw) * (x1 - x0)",
  "        const o = (j * dw + i) * 4",
  "        if (!nearDirt(wx, wy)) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        const f = dirtField(terrain, worldW, wx, wy)",
  "        const w = smoothstep(0.05, 0.52, f)",
  "        if (w < 0.03) {",
  "          data[o + 3] = 0",
  "          continue",
  "        }",
  "        let sandN = 0",
  "        const ix = Math.floor(wx)",
  "        const iy = Math.floor(wy)",
  "        for (let dy = -1; dy <= 1; dy++) {",
  "          for (let dx = -1; dx <= 1; dx++) {",
  "            const x = ix + dx",
  "            const y = iy + dy",
  "            if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "            if (terrain[y * worldW + x] === SAND) sandN++",
  "          }",
  "        }",
  "        const cover = sandN > 0 ? sand : dirtCol",
  "        const tint = simplex2(wx * 2.5, wy * 2.5) * 6",
  "        data[o] = Math.max(0, Math.min(255, (land[0] * (1 - w) + cover[0] * w + tint) | 0))",
  "        data[o + 1] = Math.max(0, Math.min(255, (land[1] * (1 - w) + cover[1] * w + tint * 0.7) | 0))",
  "        data[o + 2] = Math.max(0, Math.min(255, (land[2] * (1 - w) + cover[2] * w + tint * 0.45) | 0))",
  "        data[o + 3] = 255",
  "      }",
  "    }",
  "    const tctx = shoreTmpCanvas(dw, dh)",
  "    tctx.clearRect(0, 0, dw, dh)",
  "    tctx.putImageData(img, 0, 0)",
  "    const prev = ctx.imageSmoothingEnabled",
  "    ctx.imageSmoothingEnabled = true",
  "    ctx.drawImage(_shoreTmp!, 0, 0, dw, dh, px0, py0, pw, ph)",
  "    ctx.imageSmoothingEnabled = prev",
  "  } catch (e) {",
  "    ;(window as unknown as { __shoreErr?: string }).__shoreErr = String(e)",
  "  }",
  "}",
  "",
].join("\n")

fs.writeFileSync(p, t.slice(0, a2) + rest, "utf8")
console.log("ok", fs.readFileSync(p, "utf8").includes("One shared buffer"), fs.statSync(p).size)
