import fs from "fs"

const p = "src/lib/render/nature/shorePaint.ts"
let t = fs.readFileSync(p, "utf8")
const a = t.indexOf("export function paintViewportShoreStrip")
if (a < 0) throw new Error("missing")

const rest = [
  "export function paintViewportShoreStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const water = rgbFromPacked(atlas.color32("water"), [36, 88, 104])',
  '  const deep = rgbFromPacked(atlas.color32("water_deep"), [28, 68, 92])',
  "  const PAD = 0.85",
  "  const span = 1 + PAD * 2",
  "  const dim = Math.max(24, Math.min(72, Math.round(tileS * span)))",
  "  const inBand = (gx: number, gy: number): boolean => {",
  "    const hereW = terrain[gy * worldW + gx]! === WATER",
  "    for (let dy = -4; dy <= 4; dy++) {",
  "      for (let dx = -4; dx <= 4; dx++) {",
  "        if (dx === 0 && dy === 0) continue",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if ((terrain[y * worldW + x] === WATER) !== hereW) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  // ImageData per band cell — continuous SDF, no fillRect storm.",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!inBand(gx, gy)) continue",
  "      const img = ctx.createImageData(dim, dim)",
  "      const data = img.data",
  "      for (let j = 0; j < dim; j++) {",
  "        const wy = gy - PAD + ((j + 0.5) / dim) * span",
  "        for (let i = 0; i < dim; i++) {",
  "          const wx = gx - PAD + ((i + 0.5) / dim) * span",
  "          const f = shoreField(terrain, worldW, wx, wy)",
  "          const w1 = smoothstep(0.02, 0.52, f)",
  "          const w2 = smoothstep(0.45, 0.9, f)",
  "          const tint = simplex2(wx * 2.05, wy * 2.05) * 5",
  "          const r0 = land[0] * (1 - w1) + water[0] * w1",
  "          const g0 = land[1] * (1 - w1) + water[1] * w1",
  "          const b0 = land[2] * (1 - w1) + water[2] * w1",
  "          const o = (j * dim + i) * 4",
  "          data[o] = Math.max(0, Math.min(255, (r0 * (1 - w2) + deep[0] * w2 + tint) | 0))",
  "          data[o + 1] = Math.max(0, Math.min(255, (g0 * (1 - w2) + deep[1] * w2 + tint * 0.7) | 0))",
  "          data[o + 2] = Math.max(0, Math.min(255, (b0 * (1 - w2) + deep[2] * w2 + tint * 0.45) | 0))",
  "          data[o + 3] = 255",
  "        }",
  "      }",
  "      const px = (gx * tilePx - camX) * zoom - PAD * tileS",
  "      const py = (gy * tilePx - camY) * zoom - PAD * tileS",
  "      const prev = ctx.imageSmoothingEnabled",
  "      ctx.imageSmoothingEnabled = true",
  "      // putImageData ignores transform; draw via temp canvas for scale.",
  "      const tmp = document.createElement(\"canvas\")",
  "      tmp.width = dim",
  "      tmp.height = dim",
  "      const tctx = tmp.getContext(\"2d\")!",
  "      tctx.putImageData(img, 0, 0)",
  "      ctx.drawImage(tmp, px, py, tileS * span, tileS * span)",
  "      ctx.imageSmoothingEnabled = prev",
  "    }",
  "  }",
  "}",
  "",
  "export function paintViewportDirtStrip(",
  "  ctx: CanvasRenderingContext2D,",
  "  atlas: AtlasColor,",
  "  terrain: Uint8Array,",
  "  worldW: number,",
  "  x0: number,",
  "  y0: number,",
  "  x1: number,",
  "  y1: number,",
  "  camX: number,",
  "  camY: number,",
  "  zoom: number,",
  "  tilePx: number,",
  ") {",
  "  const tileS = tilePx * zoom",
  '  const land = rgbFromPacked(atlas.color32("grass"), [58, 90, 38])',
  '  const dirtCol = rgbFromPacked(atlas.color32("grass_grazed"), [118, 92, 52])',
  '  const sand = rgbFromPacked(atlas.color32("sand"), [210, 186, 118])',
  "  const PAD = 0.8",
  "  const span = 1 + PAD * 2",
  "  const dim = Math.max(24, Math.min(64, Math.round(tileS * span * 0.85)))",
  "  const nearDirt = (gx: number, gy: number): boolean => {",
  "    for (let dy = -3; dy <= 3; dy++) {",
  "      for (let dx = -3; dx <= 3; dx++) {",
  "        const x = gx + dx",
  "        const y = gy + dy",
  "        if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "        if (isDirtOrSand(terrain[y * worldW + x]!)) return true",
  "      }",
  "    }",
  "    return false",
  "  }",
  "  for (let gy = y0; gy < y1; gy++) {",
  "    for (let gx = x0; gx < x1; gx++) {",
  "      if (!nearDirt(gx, gy)) continue",
  "      let sandN = 0",
  "      for (let dy = -1; dy <= 1; dy++) {",
  "        for (let dx = -1; dx <= 1; dx++) {",
  "          const x = gx + dx",
  "          const y = gy + dy",
  "          if (x < 0 || y < 0 || x >= worldW || y >= worldW) continue",
  "          if (terrain[y * worldW + x] === SAND) sandN++",
  "        }",
  "      }",
  "      const cover = sandN > 0 || terrain[gy * worldW + gx] === SAND ? sand : dirtCol",
  "      const img = ctx.createImageData(dim, dim)",
  "      const data = img.data",
  "      for (let j = 0; j < dim; j++) {",
  "        const wy = gy - PAD + ((j + 0.5) / dim) * span",
  "        for (let i = 0; i < dim; i++) {",
  "          const wx = gx - PAD + ((i + 0.5) / dim) * span",
  "          const f = dirtField(terrain, worldW, wx, wy)",
  "          const w = smoothstep(0.04, 0.55, f)",
  "          const tint = simplex2(wx * 2.5, wy * 2.5) * 6",
  "          const o = (j * dim + i) * 4",
  "          data[o] = Math.max(0, Math.min(255, (land[0] * (1 - w) + cover[0] * w + tint) | 0))",
  "          data[o + 1] = Math.max(0, Math.min(255, (land[1] * (1 - w) + cover[1] * w + tint * 0.7) | 0))",
  "          data[o + 2] = Math.max(0, Math.min(255, (land[2] * (1 - w) + cover[2] * w + tint * 0.45) | 0))",
  "          data[o + 3] = w < 0.02 ? 0 : 255",
  "        }",
  "      }",
  "      const px = (gx * tilePx - camX) * zoom - PAD * tileS",
  "      const py = (gy * tilePx - camY) * zoom - PAD * tileS",
  "      const tmp = document.createElement(\"canvas\")",
  "      tmp.width = dim",
  "      tmp.height = dim",
  "      tmp.getContext(\"2d\")!.putImageData(img, 0, 0)",
  "      const prev = ctx.imageSmoothingEnabled",
  "      ctx.imageSmoothingEnabled = true",
  "      ctx.drawImage(tmp, px, py, tileS * span, tileS * span)",
  "      ctx.imageSmoothingEnabled = prev",
  "    }",
  "  }",
  "}",
  "",
].join("\n")

fs.writeFileSync(p, t.slice(0, a) + rest, "utf8")
console.log("ok", fs.readFileSync(p, "utf8").includes("ImageData per band"), fs.statSync(p).size)
